extends: airbnb
env:
  browser: true
  node: true
rules:
  comma-dangle: 0
  indent: [2, 2, {SwitchCase: 1}]
  react/jsx-filename-extension: [1, {extensions: [.js, .jsx]}]
  react/prop-types: 0
  no-array-index-key: 1
