export const Action = {
  // API call
  'FETCH_APPLIATIONS_REQUESTED' : 'FETCH_APPLIATIONS_REQUESTED',
  'FETCH_APPLICATIONS_SUCCEEDED' :  'FETCH_APPLICATIONS_SUCCEEDED',
  'FETCH_APPLICATIONS_FAILED' : 'FETCH_APPLICATIONS_FAILED',

  'CREATE_APPLICATION_REQUESTED' : 'CREATE_APPLICATION_REQUESTED',
  'CREATE_APPLICATION_SUCCEEDED' : 'CREATE_APPLICATION_SUCCEEDED',
  'CREATE_APPLICATION_FAILED' : 'CREATE_APPLICATION_FAILED'
};
