export const Action = {
  // API call
  'FETCH_APPLIATIONS_REQUESTED' : 'FETCH_APPLIATIONS_REQUESTED',
  'FETCH_APPLICATIONS_SUCCEEDED' :  'FETCH_APPLICATIONS_SUCCEEDED',
  'FETCH_APPLICATIONS_FAILED' : 'FETCH_APPLICATIONS_FAILED'
};
